### ISSUE TITLE
Big dataset: Streaming data ?

### ISSUE THREAD

**Issue by afouchet** [alexeygrigorev/libffm-python#9]
Does your implementation support having X and Y given with a generator ? 

If not, can we build amethods:
- X, y -> write FFM-formated data in file
- file -> training of the model

**Comment by alexeygrigorev** [comment]
I am not sure - I haven't tested it with generators. It probably does not matter because inside it converts the data into some internal C++ struct, so at the end it keeps everything in memory.

If the data you have is too large to keep in memory, I can suggest trying to chuck the data and training on one chunk at a time

**Comment by alexeygrigorev** [comment]
And I didn't understand your suggestion about FFM-formatted files. If you want to use files, you don't need the python wrapper and can just use the original library

**Comment by afouchet** [comment]
I thought it would be an easy solution to keep everything in python.

In the end, I did use the original library.

Thanks for the quick response

**Comment by alexeygrigorev** [comment]
Closing now - feel free to re-open in case something is missing.
Also, if you see a way to do it in python - contributions are welcome
